-- Additive bid correctness migration. It fails on duplicate legacy data rather
-- than silently deleting/merging records.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM bidding_ban_user GROUP BY product_id, user_id HAVING COUNT(*) > 1)
     OR EXISTS (SELECT 1 FROM orders WHERE product_id IS NOT NULL GROUP BY product_id HAVING COUNT(*) > 1) THEN
    RAISE EXCEPTION 'Bid integrity migration stopped: remediate duplicate bans or product orders manually';
  END IF;
END $$;

ALTER TABLE bidding_ban_user
  ADD CONSTRAINT bidding_ban_user_product_user_unique UNIQUE (product_id, user_id);
ALTER TABLE orders
  ADD CONSTRAINT orders_one_per_product_unique UNIQUE (product_id);

CREATE TABLE bid_idempotency (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation VARCHAR(40) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(user_id),
  idempotency_key VARCHAR(255) NOT NULL,
  request_fingerprint VARCHAR(128) NOT NULL,
  response_body JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT bid_idempotency_operation_user_key_unique UNIQUE (operation, user_id, idempotency_key)
);

CREATE TABLE auction_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(100) NOT NULL,
  event_version INTEGER NOT NULL,
  aggregate_id VARCHAR(64) NOT NULL,
  payload JSONB NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  delivered_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX bidding_history_product_created_idx ON bidding_history (product_id, created_at);
CREATE INDEX auction_outbox_pending_idx ON auction_outbox (delivered_at, available_at, id);
