/** Additive only. Existing duplicate records abort safely and require manual remediation. */
exports.up = async function up(knex) {
  const duplicateBans = await knex("bidding_ban_user").select("product_id", "user_id").groupBy("product_id", "user_id").havingRaw("COUNT(*) > 1");
  const duplicateOrders = await knex("orders").whereNotNull("product_id").select("product_id").groupBy("product_id").havingRaw("COUNT(*) > 1");
  if (duplicateBans.length || duplicateOrders.length) throw new Error(`Bid integrity migration stopped: duplicate bans=${duplicateBans.length}, duplicate orders=${duplicateOrders.length}. Export and remediate duplicates before retrying.`);
  await knex.schema.alterTable("bidding_ban_user", (table) => table.unique(["product_id", "user_id"], { indexName: "bidding_ban_user_product_user_unique" }));
  await knex.schema.alterTable("orders", (table) => table.unique(["product_id"], { indexName: "orders_one_per_product_unique" }));
  await knex.schema.createTable("bid_idempotency", (table) => { table.bigIncrements("id").primary(); table.string("operation", 40).notNullable(); table.integer("user_id").notNullable().references("user_id").inTable("users"); table.string("idempotency_key", 255).notNullable(); table.string("request_fingerprint", 128).notNullable(); table.jsonb("response_body").notNullable(); table.timestamp("created_at", { useTz: true }).notNullable().defaultTo(knex.fn.now()); table.unique(["operation", "user_id", "idempotency_key"], { indexName: "bid_idempotency_operation_user_key_unique" }); });
  await knex.schema.createTable("auction_outbox", (table) => { table.bigIncrements("id").primary(); table.string("event_type", 100).notNullable(); table.integer("event_version").notNullable(); table.string("aggregate_id", 64).notNullable(); table.jsonb("payload").notNullable(); table.integer("attempts").notNullable().defaultTo(0); table.timestamp("available_at", { useTz: true }).notNullable().defaultTo(knex.fn.now()); table.timestamp("delivered_at", { useTz: true }).nullable(); table.text("last_error").nullable(); table.timestamp("created_at", { useTz: true }).notNullable().defaultTo(knex.fn.now()); });
  await knex.schema.alterTable("bidding_history", (table) => table.index(["product_id", "created_at"], "bidding_history_product_created_idx"));
  await knex.schema.alterTable("auction_outbox", (table) => table.index(["delivered_at", "available_at", "id"], "auction_outbox_pending_idx"));
};
exports.down = async function down(knex) { await knex.schema.dropTableIfExists("auction_outbox"); await knex.schema.dropTableIfExists("bid_idempotency"); await knex.schema.alterTable("bidding_history", (table) => table.dropIndex(["product_id", "created_at"], "bidding_history_product_created_idx")); await knex.schema.alterTable("orders", (table) => table.dropUnique(["product_id"], "orders_one_per_product_unique")); await knex.schema.alterTable("bidding_ban_user", (table) => table.dropUnique(["product_id", "user_id"], "bidding_ban_user_product_user_unique")); };
