-- Normalize VND to exact integer storage before introducing projection fencing.
ALTER TABLE products
  ALTER COLUMN step_price TYPE bigint USING round(COALESCE(step_price, 0))::bigint,
  ALTER COLUMN start_price TYPE bigint USING round(COALESCE(start_price, 0))::bigint,
  ALTER COLUMN current_price TYPE bigint USING round(COALESCE(current_price, 0))::bigint,
  ALTER COLUMN buy_now_price TYPE bigint USING CASE WHEN buy_now_price IS NULL THEN NULL ELSE round(buy_now_price)::bigint END;

ALTER TABLE bidding_history
  ALTER COLUMN max_price TYPE bigint USING CASE WHEN max_price IS NULL THEN NULL ELSE round(max_price)::bigint END,
  ALTER COLUMN product_price TYPE bigint USING CASE WHEN product_price IS NULL THEN NULL ELSE round(product_price)::bigint END,
  ADD COLUMN event_id uuid,
  ADD COLUMN sequence bigint,
  ADD COLUMN version bigint;

ALTER TABLE products
  ADD COLUMN auction_status varchar(16) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN auction_version bigint NOT NULL DEFAULT 0,
  ADD COLUMN auction_sequence bigint NOT NULL DEFAULT 0,
  ADD CONSTRAINT products_auction_status_check
    CHECK (auction_status IN ('PENDING', 'ACTIVE', 'SOLD', 'ENDED', 'CANCELLED')),
  ADD CONSTRAINT products_money_nonnegative_check
    CHECK (
      COALESCE(step_price, 0) >= 0 AND
      COALESCE(start_price, 0) >= 0 AND
      COALESCE(current_price, 0) >= 0 AND
      (buy_now_price IS NULL OR buy_now_price >= 0)
    ),
  ADD CONSTRAINT products_auction_version_nonnegative_check CHECK (auction_version >= 0),
  ADD CONSTRAINT products_auction_sequence_nonnegative_check CHECK (auction_sequence >= 0);

UPDATE products
SET auction_status = CASE
  WHEN is_removed IS TRUE THEN 'CANCELLED'
  WHEN end_time <= NOW() THEN 'ENDED'
  WHEN start_time > NOW() THEN 'PENDING'
  ELSE 'ACTIVE'
END;

ALTER TABLE orders
  ADD COLUMN public_order_id uuid NOT NULL DEFAULT gen_random_uuid(),
  ADD COLUMN auction_sequence bigint;

ALTER TABLE auction_outbox
  ADD COLUMN event_id uuid NOT NULL DEFAULT gen_random_uuid();

CREATE UNIQUE INDEX bidding_history_event_id_unique
  ON bidding_history(event_id) WHERE event_id IS NOT NULL;
CREATE UNIQUE INDEX bidding_history_product_sequence_unique
  ON bidding_history(product_id, sequence) WHERE sequence IS NOT NULL;
CREATE UNIQUE INDEX orders_public_order_id_unique ON orders(public_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS orders_one_per_product_unique ON orders(product_id);
CREATE UNIQUE INDEX auction_outbox_event_id_unique ON auction_outbox(event_id);

CREATE TABLE auction_processed_events (
  event_id uuid PRIMARY KEY,
  redis_entry_id varchar(64) NOT NULL UNIQUE,
  product_id bigint NOT NULL,
  sequence bigint NOT NULL,
  version bigint NOT NULL,
  processed_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT auction_processed_product_sequence_unique UNIQUE(product_id, sequence)
);

CREATE TABLE auction_transitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id uuid NOT NULL UNIQUE,
  product_id bigint NOT NULL,
  event_type varchar(64) NOT NULL,
  sequence bigint NOT NULL,
  version bigint NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT auction_transition_product_sequence_unique UNIQUE(product_id, sequence)
);

CREATE INDEX auction_transition_product_version_idx
  ON auction_transitions(product_id, version);
